package elya.constants.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

/**
 * Enumeration of standardized keys used to extract and map status-related metadata from API responses.
 * These keys correspond to the structure of status information generated by the emulator.
 */
@Getter
@AllArgsConstructor
public enum StatusInfo {

    /**
     * The JSON key representing the numeric HTTP status code (e.g., 200, 404).
     */
    STATUS("status"),

    /**
     * The JSON key representing the HTTP status series (e.g., SUCCESSFUL, CLIENT_ERROR).
     */
    SERIES("series"),

    /**
     * The JSON key representing the human-readable description of the status (e.g., OK, Not Found).
     */
    REASON("reason");

    /**
     * The literal string value used as a key in JSON or Map structures.
     */
    private final String statusInfo;

    @Override
    public String toString() {
        return statusInfo;
    }
}