spring.autoconfigure.exclude=\
# Disables Spring Data MongoDB repositories support
    org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,\
# Disables automatic Liquibase database migrations
    org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration,\
# Disables automatic DataSource (JDBC) configuration
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
# Disables Hibernate and JPA (ORM) auto-setup - These are for SQL databases
    org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
# Disables Spring Security OAuth2 Client auto-configuration
    org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration